import MenuPanel from '../components/panels/MenuPanel';
import SettingsPanel from '../components/panels/SettingsPanel';
import TodoPanel from '../components/panels/TodoPanel';

export default class PanelsService {
    static panels = [
        {
            key: 'systems',
            name: 'Core Systems',
            shortName: 'Core Systems',
            route: '/systems',
            icon: 'blur_circular',
            tabs: true,
            drawer: true,
            menu: true,
            component: TodoPanel,
        },
        {
            key: 'flight',
            name: 'Flight & Navigation',
            shortName: 'Flight',
            route: '/flight',
            icon: 'explorer',
            tabs: true,
            drawer: true,
            menu: true,
            component: TodoPanel,
        },
        {
            key: 'power',
            name: 'Power Management',
            shortName: 'Power',
            route: '/power',
            icon: 'battery_charging_full',
            tabs: true,
            drawer: true,
            menu: true,
            component: TodoPanel,
        },
        {
            key: 'shields',
            name: 'Shield Management',
            shortName: 'Shields',
            route: '/shields',
            icon: 'security',
            tabs: true,
            drawer: true,
            menu: true,
            component: TodoPanel,
        },
        {
            key: 'combat',
            name: 'Targeting & Combat',
            shortName: 'Combat',
            route: '/combat',
            icon: 'gps_fixed',
            tabs: true,
            drawer: true,
            menu: true,
            component: TodoPanel,
        },
        {
            key: 'industrial',
            name: 'Industrial',
            shortName: 'Industrial',
            route: '/industrial',
            icon: 'wifi_tethering',
            tabs: false,
            drawer: true,
            menu: true,
            component: TodoPanel,
        },
        {
            key: 'comms',
            name: 'Communications',
            shortName: 'Comms',
            route: '/comms',
            icon: 'headset',
            tabs: false,
            drawer: true,
            menu: true,
            component: TodoPanel,
        },
        {
            key: 'settings',
            name: 'Settings',
            shortName: 'Settings',
            route: '/settings',
            icon: 'settings',
            tabs: true,
            drawer: true,
            menu: true,
            component: SettingsPanel,
        },
        {
            key: 'menu',
            name: 'Menu',
            shortName: 'Menu',
            route: '/menu',
            icon: 'home',
            tabs: false,
            drawer: false,
            menu: false,
            component: MenuPanel,
        },
    ]

}